# Generated by Django 4.0.4 on 2022-05-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('descrption', models.CharField(max_length=250)),
            ],
        ),
    ]
